---
title: "ARM Vis"
author: "Yunzhi Kong"
date: "10/18/2020"
output: html_document
---


```{r}
ReviewTrans <- read.transactions("UpdatedTNegFile.csv", sep =",", 
                                format("basket"),  rm.duplicates = TRUE)
ReviewTrans_rules = arules::apriori(ReviewTrans, 
        parameter = list(support=.01, conf=0.01, minlen=2))
```


## Visulization

### Top 20 Frequent words

```{r}
## Plot of which items are most frequent
itemFrequencyPlot(ReviewTrans, topN=20, type="absolute",col = rainbow(7),xlab = "Top 20 frequent words", ylab = "Count")
```


#### Targeting Food rules LHS

```{r}

FoodRule <- apriori(ReviewTrans,parameter = list(supp=.01, conf=.01, minlen=2),
                     appearance = list(default="rhs", lhs="food"),
                     control=list(verbose=FALSE))
FoodRule_C <- sort(FoodRule, decreasing=TRUE, by="confidence")
FoodRule_S <- sort(FoodRule, decreasing=TRUE, by="support")
FoodRule_L <- sort(FoodRule, decreasing=TRUE, by="lift")


inspect(FoodRule_C[1:15])
inspect(FoodRule_S[1:15])
inspect(FoodRule_L[1:15])
```



```{r}
plot(FoodRule_C[1:15], method="graph", 
     by = 'confidence',control=list(type="itemsets"), 
     main = 'Food Rules by confidence', shading = 'confidence')

plot(FoodRule_S[1:15], method="graph", 
     by = 'support',control=list(type="itemsets"), 
     main = 'Food Rules by support', shading = 'support')

plot(FoodRule_L[1:15], method="graph", 
     by = 'lift',control=list(type="itemsets"), 
     main = 'Food Rules by lift', shading = 'lift')

```



### Top 15 three measures visulizations

```{r}
library(igraph)
subrules <- head(sort(ReviewTrans_rules, by="support", decreasing=TRUE),15)
plot(subrules,main="Scatter plot for Top 15 Support")
plot(subrules, method="graph", engine="interactive")


subrules <- head(sort(ReviewTrans_rules, by="confidence", decreasing=TRUE),15)
plot(subrules,main="Scatter plot for Top 15 Confidence")
plot(subrules, method="graph", engine="interactive")


subrules <- head(sort(ReviewTrans_rules, by="lift", decreasing=TRUE),15)
plot(subrules,main="Scatter plot for Top 15 Lift")
plot(subrules, method="graph", engine="interactive")
```




## NetworkD3

```{r}
Rules_DF2<-DATAFRAME(ReviewTrans_rules, separate = TRUE)
(head(Rules_DF2))
str(Rules_DF2)
## Convert to char
Rules_DF2$LHS<-as.character(Rules_DF2$LHS)
Rules_DF2$RHS<-as.character(Rules_DF2$RHS)

## Remove all {}
Rules_DF2[] <- lapply(Rules_DF2, gsub, pattern='[{]', replacement='')
Rules_DF2[] <- lapply(Rules_DF2, gsub, pattern='[}]', replacement='')

head(Rules_DF2)


```

```{r}

## Remove the sup, conf, and count
## USING LIFT
Rules_L<-Rules_DF2[c(1,2,6)]
names(Rules_L) <- c("SourceName", "TargetName", "Weight")
head(Rules_L,30)

## USING SUP
Rules_S<-Rules_DF2[c(1,2,3)]
names(Rules_S) <- c("SourceName", "TargetName", "Weight")
head(Rules_S,30)

## USING CONF
Rules_C<-Rules_DF2[c(1,2,4)]
names(Rules_C) <- c("SourceName", "TargetName", "Weight")
head(Rules_C,30)

## CHoose and set
#Rules_Sup<-Rules_C
Rules_Sup<-Rules_L
#Rules_Sup<-Rules_S

```

```{r}
edgeList<-Rules_Sup
MyGraph <- igraph::simplify(igraph::graph.data.frame(edgeList, directed=TRUE))

nodeList <- data.frame(ID = c(0:(igraph::vcount(MyGraph) - 1)), 
                       # because networkD3 library requires IDs to start at 0
                       nName = igraph::V(MyGraph)$name)
## Node Degree
(nodeList <- cbind(nodeList, nodeDegree=igraph::degree(MyGraph, 
                    v = igraph::V(MyGraph), mode = "all")))

## Betweenness
BetweenNess <- igraph::betweenness(MyGraph, 
      v = igraph::V(MyGraph), 
      directed = TRUE) 

(nodeList <- cbind(nodeList, nodeBetweenness=BetweenNess))

## This can change the BetweenNess value if needed
BetweenNess<-BetweenNess/100


```

```{r}
getNodeID <- function(x){
  which(x == igraph::V(MyGraph)$name) - 1  #IDs start at 0
}
#(getNodeID("1")) 

edgeList <- plyr::ddply(
  Rules_Sup, .variables = c("SourceName", "TargetName" , "Weight"), 
  function (x) data.frame(SourceID = getNodeID(x$SourceName), 
                          TargetID = getNodeID(x$TargetName)))

head(edgeList)
nrow(edgeList)
```

```{r}
########################################################################
##############  Dice Sim ################################################
###########################################################################
#Calculate Dice similarities between all pairs of nodes
#The Dice similarity coefficient of two vertices is twice 
#the number of common neighbors divided by the sum of the degrees 
#of the vertices. Method dice calculates the pairwise Dice similarities 
#for some (or all) of the vertices. 
DiceSim <- igraph::similarity.dice(MyGraph, vids = igraph::V(MyGraph), mode = "all")
head(DiceSim)

#Create  data frame that contains the Dice similarity between any two vertices
F1 <- function(x) {data.frame(diceSim = DiceSim[x$SourceID +1, x$TargetID + 1])}
#Place a new column in edgeList with the Dice Sim
head(edgeList)
edgeList <- plyr::ddply(edgeList,
                        .variables=c("SourceName", "TargetName", "Weight", 
                                               "SourceID", "TargetID"), 
                        function(x) data.frame(F1(x)))
head(edgeList)
```

```{r}
##################################################################################
##################   color #################################################
######################################################
COLOR_P <- colorRampPalette(c("#00FF00", "#FF0000"), 
                            bias = nrow(edgeList), space = "rgb", 
                            interpolate = "linear")
COLOR_P
(colCodes <- COLOR_P(length(unique(edgeList$diceSim))))
edges_col <- sapply(edgeList$diceSim, 
                    function(x) colCodes[which(sort(unique(edgeList$diceSim)) == x)])
nrow(edges_col)


```

```{r}
library(networkD3)
D3_network_Reviews <- networkD3::forceNetwork(
  Links = edgeList, # data frame that contains info about edges
  Nodes = nodeList, # data frame that contains info about nodes
  Source = "SourceID", # ID of source node 
  Target = "TargetID", # ID of target node
  Value = "Weight", # value from the edge list (data frame) that will be used to value/weight relationship amongst nodes
  NodeID = "nName", # value from the node list (data frame) that contains node description we want to use (e.g., node name)
  Nodesize = "nodeBetweenness",  # value from the node list (data frame) that contains value we want to use for a node size
  Group = "nodeDegree",  # value from the node list (data frame) that contains value we want to use for node color
  height = 700, # Size of the plot (vertical)
  width = 900,  # Size of the plot (horizontal)
  fontSize = 20, # Font size
  linkDistance = networkD3::JS("function(d) { return d.value*10; }"), # Function to determine distance between any two nodes, uses variables already defined in forceNetwork function (not variables from a data frame)
  linkWidth = networkD3::JS("function(d) { return d.value/10; }"),# Function to determine link/edge thickness, uses variables already defined in forceNetwork function (not variables from a data frame)
  opacity = 0.9, # opacity
  zoom = TRUE, # ability to zoom when click on the node
  opacityNoHover = 0.9, # opacity of labels when static
  linkColour = "red"   ###"edges_col"red"# edge colors
) 

# Plot network
#D3_network_Reviews

# Save network as html file
networkD3::saveNetwork(D3_network_Reviews, 
                       "NetD3_top20_Lift.html", selfcontained = TRUE)

```
